version: '3.4'

services:
  # Craetes Microsoft Sql Server 
  SQLServer:
    container_name: PaymentGateway.Database
    image: mcr.microsoft.com/mssql/server:2019-latest #mcr.microsoft.com/azure-sql-edge:latest
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=test_password23
    ports: 
      - "1433:1433"

  # Creates Api Service for Payment Gateway
  PaymentGatewayService:
    container_name: PaymentGateway.Service
    restart: always
    image: paymentgatewayapi:1.0.0
    build:
      context: .
      dockerfile: DockerfileMerchantApi
    expose: 
      - "80"
    ports:
      - "8000:80"
    environment: 
      - ConnectionStrings:PaymentGatwayConnection=SQLServer 
      - BankApiBaseAddress=BankService
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - SQLServer

  # Creates Api Service for Bank 
  BankService:
    container_name: Bank.Service
    restart: always
    image: bankserviceapi:1.0.0
    build:
      context: .
      dockerfile: DockerfileBankApi
    ports:
      - "8001:80"
